image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  test: "Tests"

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "docker pull mcr.microsoft.com/mssql/server:2017-latest"
    - "docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=<SomeStrong!Passw0rd> -p 1433:1433 --name sql1 -d mcr.microsoft.com/mssql/server:2017-latest"
    - "dotnet build"

test:
  stage: test
  script:
    - "cd $test"
    - "dotnet test"
