image: microsoft/dotnet:latest
services:
  - name: microsoft/mssql-server-linux:latest
    alias: sql

stages:
  - build
  - publish

variables:
  test: "Tests"
  ACCEPT_EULA: "Y"
  SA_PASSWORD: SomeStrong!Passw0rd

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"

publish:
  stage: publish
  script:
    - "dotnet tool install --global GitVersion.Tool --version 5.0.0-beta2-6"
    - 'export PATH="$PATH:/root/.dotnet/tools"'
    - "echo $(dotnet-gitversion ./ -showvariable FullSemVer)"
    - 'dotnet pack -p:PackageVersion="$(dotnet-gitversion ./ -showvariable FullSemVer)"'
    - "dotnet nuget push ./SharpCheddar.Core/bin/Debug/SharpCheddar.Core*.nupkg -k $sharpcheddar_nuget_key -s https://api.nuget.org/v3/index.json"
    - "dotnet nuget push ./SharpCheddar.EntityFrameworkCore/bin/Debug/SharpCheddar.EFCore*.nupkg -k $sharpcheddar_nuget_key -s https://api.nuget.org/v3/index.json"
