image: microsoft/dotnet:latest
services:
  - name: microsoft/mssql-server-linux:latest
    alias: sql

stages:
  - build
  - test

variables:
  test: "Tests"
  ACCEPT_EULA: "Y"
  SA_PASSWORD: SomeStrong!Passw0rd

before_script:
  - "dotnet restore"

after_script:
  - "dotnet pack"
  - "dotnet nuget push ./SharpCheddar.Core/bin/Debug/SharpCheddar.Core*.nupkg -k $sharpcheddar_nuget_key -2 https://api.nuget.org/v3/index.json"
  - "dotnet nuget push ./SharpCheddar.EntityFrameworkCore/bin/Debug/SharpCheddar.EntityFrameworkCore*.nupkg -k $sharpcheddar_nuget_key -2 https://api.nuget.org/v3/index.json"

build:
  stage: build
  script:
    - "dotnet build"

test:
  stage: test
  script:
    - "cd $test"
    - "dotnet test"
