image: microsoft/mssql-server-windows-developer:latest

stages:
  - build
  - test

variables:
  test: "Tests"

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"

test:
  stage: test
  script:
    - "cd $test"
    - "dotnet test"
